baseURL = "https://ta2ozq.me"
languageCode = "tr-tr"
title = "TA2OZQ - Özcan Oğuz"
theme = "hugo-theme-cactus"
author = "Özcan Oğuz"
copyright = "Özcan Oğuz" # cactus will use title if copyright is not set

# summaryLength = 2

# Main menu which appears below site header.
[[menu.main]]
name = "ana sayfa"
url = "/"
weight = 1

[[menu.main]]
name = "yazılar"
url = "/yazilar"
weight = 2

[[menu.main]]
name = "konular"
url = "/tags"
weight = 3

[[menu.main]]
name = "hakkında"
url = "/about"
weight = 4

[markup]
  [markup.tableOfContents]
    endLevel = 4
    ordered = false
    startLevel = 2

[params]
  logo = "/avatar.jpg"
  colortheme = "light" # dark, light, white, or classic
  rss = true # generate rss feed. default value is false
  googleAnalyticsAsync = true # use asynchronous tracking. Synchronous tracking by default

  # Home page settings
  description = "Ben Özcan Oğuz, 2013 yılından beridir radyo amatörlüğü yapmaya çalışıyorum."
  mainSection = "posts" # your main section
  showAllPostsOnHomePage = true # default
  postsOnHomePage = 5 # this option will be ignored if showAllPostsOnHomePage is set to true
  tagsOverview = true # show tags overview by default.
  showProjectsList = true # show projects list by default (if projects data file exists).
  projectsUrl = "https://github.com/ooguz" # title link for projects list

  # https://gohugo.io/functions/format/#hugo-date-and-time-templating-reference
  dateFormat = "2006-01-02" # default

  # Post page settings
  show_updated = true # default

  [params.comments]
    enabled = false # default
    engine = "disqus" # more supported engines will be added.

  # the value of name should be an valid font awesome icon name (brands type)
  # https://fontawesome.com/icons?d=gallery&s=brands
  [[params.social]]
    name = "github"
    link = "https://github.com/ooguz"
  [[params.social]]
    name = "twitter"
    link = "https://twitter.com/ooguz"
  [[params.social]]
    name = "email"
    link = "ta2ozq@riseup.net"  # no need for "mailto:" in the head
